data class ShopDetail(
    val achived_amount: Int,
    val address: String,
    val balance_amount: Int,
    val balance_amt: Int,
    val category_name: String,
    val city: String,
    val delivery: String,
    val items: String,
    val paid_amt: Int,
    val pincode: String,
    val shopId: Int,
    val shop_distance: Int,
    val shop_id: String,
    val shop_name: String,
    val shop_total: Int,
    val target_amount: Int,
    val units_name: String
)